### PR TITLE
Remove legacy rviz plugins

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@mpowelson In the process I noticed that I forgot to port the planning archives plugin. Do you feel this is still needed or can it be removed?

**Comment by mpowelson** [comment]
> @mpowelson In the process I noticed that I forgot to port the planning archives plugin. Do you feel this is still needed or can it be removed?

I'd probably prefer to keep it until we replace it. I don't think we have any public tools for logging/viewing planning requests yet do we? That said, I probably won't use this much anymore, so I don't feel strongly.

**Comment by Levi-Armstrong** [comment]
Sounds good, I will hold off merging until there is a solution is available. I have never used the tool, do you mind explaining how it currently works? Is it just for view resulting trajectory or can you replan the trajectory?

**Comment by Levi-Armstrong** [comment]
It looks like if add support to the trajectory widget to load a motion planning problem it will provide the same functionality. Does that work for you?

**Comment by mpowelson** [comment]
Sure that's fine.

**Pull request merged**
